# This is a basic workflow to help you get started with Actions

name: OWASP ZAP

on:
  workflow_dispatch:
    
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://devopslab-felipe.herokuapp.com/'
          cmd_options: '-a'
